services:
  auth-api:
    image: public.ecr.aws/q2n5r5e8/ozrnds/shkedia-photo-upload-service:${GALLERY_BACKEND_VERSION}
    container_name: upload_api
    env_file: .local/upload_service_${ENVIRONMENT}.env
    environment:
      - JWT_KEY_LOCATION
      - TOKEN_TIME_PERIOD
      - ENVIRONMENT
      - MEDIA_DB_HOST
      - MEDIA_DB_PORT
      - MEDIA_REPO_HOST
      - MEDIA_REPO_PORT
      - USER_DB_HOST
      - USER_DB_PORT
      - THUMBNAIL_MAX_HEIGHT
      - THUMBNAIL_MAX_WIDTH
      - PUBLIC_KEY_LOCATION
      - PRIVATE_KEY_LOCATION=""
    expose:
      - "5000"
    ports:
      - "4433:5000"
    volumes:
      - ${HOST_MOUNT}:/temp
    # restart: always